export {default as Header} from './header/Header'
export {default as FoodCard} from './FoodCard/FoodCard'
export {default as MenuList} from './MenuList/MenuList'
export {default as Footer} from './Footer/Footer'
export {default as MainMenuSection} from './MainMenuSection/MainMenuSection'